### ISSUE TITLE
Alternate syntaxe is better

### ISSUE THREAD

**Issue by xooxdoo** [gilbert/es-explicit-this#1]
IMHO the alternate syntax looks better and makes the **This-Binding Syntax** spec syntax unambiguous.

I prefer writing:

```
function array::split(index) {
   return [array.slice(0, index), array.slice(index)];
}

// very transparent
```

than:

```
function split(this array, index) {
//                    ^-- you are telling i can write `this` here and not further down, y u do `this` 2 me :D
  return [array.slice(0, index), array.slice(index)];
}
```

**Comment by xooxdoo** [comment]
also it looks like coffee script syntax for prototype `array::split` except that if you reference `this` you wil make JavaScript angry :smile:

**Comment by Ltrlg** [comment]
This is why I like it too, but it does not work well with anonymous functions expressions, e.g.

``` js
doAsync( function result ::( amount ) {
    result.amount += 2;
} );
```

And TypeScript/Flow would have _many_ colons:

``` js
function a: number :: add( b: number ): number {
    return a + b;
};
```

**Comment by xooxdoo** [comment]
I'm currently making a language and your feature and the other will have a place in it :D

the following is the MD file describing it 

---

# Meta
- **Type**:
  `syntax`
- **Status**:
  `Accepted`
- **Created**: 
  `4/4/2016 4:18:13 AM`
- **Accepted**:
  `4/4/2016 5:38:09 AM`
- **Author**: `xooxdoo`
- **Inspiration**: [**ES7.stage0** This-bind function _proposal_] & [**ES7.preStage0** Explicit this naming _proposal_'s Alternate syntaxe]

# Usage

<table width="100%"><tr><td>Linjo
<pre>array::Add(item) {
  array.push(item);
  return array;
}
// with types
JSArray&lt;T> &lt;array is JSArray&lt;T>>::Add(T item) { 
  array.push(item);
  return array;
}
a = [0, 2, 3]::Add(0);
</pre></td><td>JS without optimization
<pre>function Add(item) {
  this.push(item);
  return this;
}
a = Add.call([0, 2, 3], 0);
</pre></td><td>JS with optimization
<pre>//> inlined array::Add(item)
{
  let $ = [0, 2, 3];
  $.push(0);
  a = $;
}
</pre></td></tr></table>

`function Add(item) { ... }`  will probably be `function Add__virt__`; so it dosnt conflict with a function with the same name.

`Add.call([0, 2, 3], 0)` will probably be `util__.call__(Add, [0, 2, 3], 0)`.

# Errors

Like inside functions using `this` is forbidden, throw.

# Syntaxe

<p><pre>VirtualMethodDeclaration
  : VirtualMethodHead FunctionBody
  ;
VirtualMethodHead
  : ReturnType? (identifier | &lt;TypeHint identifier>) '::' identifier '(' FunctionParameterList ')'
  ;
FunctionBody
  : ...
  ;
FunctionParameterList
  : ...
  ;
</pre></p>

# Notes

nope.

# Issues

nope.

# Changes
- `4/4/2016 4 AM` :
  - Initial draft
- `4/4/2016 4 AM` :
  - Added syntax
  - Added error when this is used.

**Comment by xooxdoo** [comment]
As you can see my type hint syntax is like C.

here what i was going for...

```
JSArray<T> array::Add(T item) array is JSArray<T> { 
  array.push(item);
  return array;
}
```

then i thought, why not ...

```
JSArray<T> array<JSArray<T>>::Add(T item) { 
  array.push(item);
  return array;
}
```

or even ...

```
JSArray<T> ::Add(this = JSArray<T> array, T item) { 
  array.push(item);
  return array;
}
```

then i decided

```
JSArray<T> <array is JSArray<T>>::Add(T item) { 
  array.push(item);
  return array;
}
```

**Comment by xooxdoo** [comment]
I need to stop talking about the language here.

So the point is:
- I'm really grateful stumbled on your spec and especially read the alternate syntax section
- Your idea is brilliant, don't be disappointed if they don't approve it, because it surely will be used in my language
- It suits JavaScript new direction of removing monkey patches and replacing them with good syntax or Reflection APIs
- It complete the other spec; By the way you should definitely merge those specs together, i think.

**Comment by xooxdoo** [comment]
Lastly the syntax

```
function zip (this array, otherArray) {
  return array.map( (a, i) => [a, otherArray[i]] )
}
```

I saw a document for maybe SoundScript, i cant remember, and it contained the following syntax

```
function foo(this : SomeType) : SomeOtherType {}
```

They want to enable typing of `this`.

i this is what the TypeScript/Flow also want to achieve
then TypeScript/Flow/SoundScript code would become:

```
function zip<T>(this array : Array<T>, otherArray: <T>) {
  return array.map( (a, i) => [a, otherArray[i]] )
}
```

And by writing writing this last snippet i got inspired and found a better syntax for my use.
