### ISSUE TITLE
Allow `this` inside the body if no explicit name provided

### ISSUE THREAD

**Issue by hax** [gilbert/es-explicit-this#3]
**Update: `function(this) {}` already be supported by TS from 2016, also supported by [Closure compiler](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System) (search "function this type"), and also have [PR in Flowtype](https://github.com/facebook/flow/pull/7807).**

Original comment:

This is the example of current proposal:

``` js
function method (this elem, e) {
  console.log("Elem:", elem) // OK
  console.log("this:", this) // <-- Throws an error!
}
```

I suggest allow `this` inside the body if no explicit name provided, so we can write:

``` js
function method (this, e) {
  console.log("this:", this) // <-- That's ok
}
```

Though it looks redundant, it will be useful for type annotation (See https://github.com/Microsoft/TypeScript/pull/6739 and https://github.com/facebook/flow/issues/452#issuecomment-110286919), and linter (See http://eslint.org/docs/rules/no-invalid-this and http://eslint.org/docs/rules/prefer-arrow-callback#allowunboundthis).

---

**Update: I changed my mind that this part should be leave to linters.**

Original comments:

And current proposal allow `this` in inner functions:

``` js
runTask(function cb (this elem, e) {

  elem.runAsyncTask(function () {
    console.log("Outer elem:", elem) // OK
    console.log("Inner this:", this) // OK
  });
})
```

I suggest do not allow it, but require adding `this` in the arguments:

``` js
runTask(function cb (this elem, e) {

  elem.runAsyncTask(function () {
    console.log("Outer elem:", elem) // OK
    console.log("Inner this:", this) // Syntax error
  });
  elem.runAsyncTask(function (this) {
    console.log("Outer elem:", elem) // OK
    console.log("Inner this:", this) // OK
  });
})
```

**Comment by gilbert** [comment]
Allowing for no explicit name seems good to me.

Wouldn't making it required break backwards compatibility?

**Comment by hax** [comment]
As I understand, it won't break backwards compatibility. `this` in parameter position is syntax error now. For example `new Function('this', '')` throw SyntaxError.
